apiVersion: v1
kind: Service
metadata:
  name: {{ include "suterchain.fullname" . }}
  labels:
{{ include "suterchain.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9933
      targetPort: 9933
      protocol: TCP
      name: http
    - port: 9944
      targetPort: 9944
      protocol: TCP
      name: websocket
    - port: 30333
      targetPort: 30333
      protocol: TCP
      name: tcp
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
  selector:
    app.kubernetes.io/name: {{ include "suterchain.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
