{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suterchain.serviceAccountName" . }}
  labels:
{{ include "suterchain.labels" . | indent 4 }}
{{- end -}}
